/*
  Cursed Boardgame Interactive NSFWCYOA
  Created by /u/chinesesilklanterns
  May 2020
    
  I hope you enjoyed playing this as much as I did making it. 
  If you want to contact me, find me on Reddit (https://reddit.com/u/chinesesilklanterns)
  If you've found content that you think I might enjoy, do share it with me!
  
  License: You are free to use and redistribute this game, associated code and files entirely free of charge in a non-commercial setting, so long as proper attribution is given to me. 
  I do not own the copyright to the illustrated images in the 'icons' folder used in this game, they belong to various artists found online.
  You agree not to hold me responsible for any damages that may result from your use of these files, use at your own risk.
  You may create derivative works, using all or parts of the files provided here, as long as the abovementioned acknowledgement is retained.
  
  Basically, if you share or modify this, be nice and credit me.
*/

//cell types
//Teleportation Portal - Provides the option of moving forward X number of steps or staying put
//Cursed Teleportation Portal - Provides the option of staying put with a penalty, or moving back X number of steps 
//Transformation Shrine - Provides a standard perk to choose
//Cursed Transformation Shrine - Provides a different kind of perk to choose
//Treasure Chest - Contains unknown items or currency. May be trapped. Items may be cursed.
//Item Shop - Sells items.
//Wild Magic - Applies unpredictable effect


var configCells = [
  {cellid:[3,9,18,25,32,41,49,56,71,83], category: "Transformation", imagebig:"shrine1big.png", image:"shrine1.png", title:"Transformation Shrine", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>Your body and mind may be improved to better serve you in the coming trials.</em></span><br/><br/>Looks like you'll have to make a choice...", numans: 3},
  {cellid:[2,4,5,6,8,10,12,14,16,19,21,23,26,28,34,37,38,40,45,47,50,52,53,58,61,65,66,69,70,72,74,77,82,84,89,92,93,96,97], category: "CursedTransformation", imagebig:"shrine2big.png", image:"shrine2.png", title:"Cursed Transformation Shrine", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>Your punishment continues. Select a curse to bear.</em></span><br/><br/>Looks like you'll have to make a choice...", numans: 3},
  {cellid:[11,24,35,51], category: "Teleport", imagebig:"portal1big.jpg", image:"portal1.png", title:"Teleportation Portal", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>Life offers many paths. Beware. The shortest route is not always best.</em></span><br/><br/>A number of options appear to skip ahead on the board...", numans: 0},
  {cellid:[29,36,44,54,60,63,73,76,79,87,88,90,95,99], category: "CursedTeleport", imagebig:"portal2big.jpg", image:"portal2.png", title:"Cursed Teleportation Portal", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>Your punishment continues. Accept this curse, or retreat and risk further punishment.</em></span><br/><br/>Looks like you'll have to make a choice...",  numans: 0},
  {cellid:[7,13,17,27,30,33,39,43,48,55,59,64,68,78,85,91], category: "TreasureChest", imagebig:"chestbig.png", image:"chest.png", title:"Mysterious Chest", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>We offer a chance at the financial support you'll need for the trails ahead. Beware. All that glitters isn't gold.</em></span><br/><br/>A loot chest appears on screen. Do you risk opening it?", numans: 0},
  {cellid:[15,20,22,31,42,46,57,62,67,75,80,81,86,94,98], category: "WildMagic", imagebig:"chaosbig.jpg", image:"chaos.png", title:"Wild Magic Surge", prompt: "Glowing letters appear on the terminal, forming a phrase.<br/><br/><span style='color:lime'><em>Your punishment continues. Fate has chosen a curse for you to bear.</em></span><br/><br/>The terminal flashes, revealing the curse.", numans: 0},
  
//{cellid:[26,27,28], category: "CursedItemShop", imagebig:"shop2big.jpg", image:"shop2.png", title:"Sketchy Dealer", prompt: "A shady looking guy appears out of nowhere.<br/><br/><span style='color:yellow'><em>\"Listen, I've some good stuff I gotta ditch quick. Take your pick - it's on the house. No refunds.\"</em></span><br/><br/>He offers you the choice of a single item.", numans: 0},

];

var itemshopdata = {cellid:[], category: "ItemShop", imagebig:"shop1big.jpg", image:"shop1.png", title:"Item Shop", prompt: "The terminal flashes, changing to display an in-game item shop.<br/><br/><span style='color:lime'><em>You may spend any currency you've acquired on items to ease your journey.</em></span><br/><br/>A number of items are listed below. Would you like to buy anything?", numans: 3};

//cell values range from 0 to max

var configAttribDescs = [
{attribname: "gender", descs: ["M","F"]},
{attribname: "strength", descs: ["Her limbs are slender and delicate. She might need help lifting more than a few pounds.","Her strength is perfectly average.","She's pretty strong physically, her body is fit and well-toned.","She's incredibly strong, her muscular form is chiseled and firm. She could lift hundreds of pounds effortlessly."]},
{attribname: "stamina", descs: ["She gets easily tired from physical activity. She'll frequently need time to rest and catch her breath.","Her stamina is perfectly average.","Her stamina is higher than average, she could run a mile without breaking a sweat.","Her stamina is inexhaustible, she could easily keep going for days."]},
{attribname: "dexterity", descs: ["She's kinda clumsy at times, but in an adorable way.","Her dexterity is perfectly average.","She's nimble and light on her feet. Her movements are graceful and precise.","She's extremely dexterous and flexible. She moves with unmatched grace and her reflexes are swift as lightning."]},
{attribname: "eyesight", descs: ["She's rather short sighted. She needs to wear glasses.","Her eyesight is perfectly average.","She has perfect vision. She can see objects clearly from miles away."]},
{attribname: "constitution", descs: ["Her constitution is perfectly average.","She's more hardy than normal. She gets sick less often and recovers faster.","She is always in perfect health, ages 5x slower, and is immune to all illnesses and diseases."]},
{attribname: "intelligence", descs: ["Her intelligence is perfectly average.","She's quick-witted, has a good memory, and often catches the little details others might miss","She's easily a genius. She has an eidetic memory, and is capable of recognizing patterns and drawing deductions that no one else can."]},
{attribname: "charisma", descs: ["She's shy and socially awkward, finding it difficult to talk to others, especially strangers.","Her charisma is perfectly average.","She's generally likable and good with people. Socializing comes naturally to her.","She's a social butterfly. Wherever she goes, she'll find that everyone adores and respects her."]},
{attribname: "talent", descs: ["Her talent is perfectly average.","She's naturally talented in many things. Whether it's music, the arts, or another hobby, so long as she puts in some effort she picks it up intuitively.","She's astoundingly gifted at whatever she does. From learning a new language, picking up a skill, to playing an instrument, it all comes easily and instinctively to her."]},
{attribname: "luck", descs: ["She seems to have the worst luck, often find herself caught in compromising situations.","Her luck is perfectly average.","She finds that things generally tend to go well for her in small, subtle ways.","She's favored by the universe. She has inexplicable luck that always seems to kick in at just the right moment. Good things regularly happen to her and those around her."]},
{attribname: "hair length", descs: ["Cropped","Neck length","Shoulder length","Long and flowing","Floor length"]},
{attribname: "breast size", descs: ["A-Cup. Tiny, fun sized mounds.","B-Cup. Small and perky.","C-Cup. Round and perky.","D-Cup. Full and busty.","E-Cup. Large and squishy.","F-Cup. Huge and pillowy.","G-Cup. Absolutely massive.","H-Cup. Back-breaking."]},
{attribname: "ass size", descs: ["Cute and petite.","Toned and round.","Curvy and bubbly.","Thicc and juicy."]},
{attribname: "physique", descs: ["She is a woman, with everything that entails.","She's an attractive woman. Your eyes are drawn to her body and cute face.","She's become a very feminine and sexy woman. Every part of her oozes sensuality, from her boobs down to her curvy waist, hips and ass, and gorgeous face."]},
{attribname: "orientation", descs: ["She is attracted to women.","She is attracted to men.","She is bisexual."]},
{attribname: "increased libido", descs: ["","Her libido is higher than normal. She's going to find herself feeling the need for release more often.","Her libido is significantly higher than normal. She'll get hot and bothered many times a day, as she'll feel an almost irresistable urge for an orgasm.","Her libido is completely out of control. Her body is near-constantly horny and aching with a desperate need multiple times a day. If she isn't having sex, she's thinking about it."]},
{attribname: "increased sensitivity", descs: ["","Her body is especially sensitive to touch. A careless brush across her skin would create a wave of pleasant shivers.","Her body's is extremely sensitive to touch. A gentle carass would leave her squirming and panting. Wearing tight clothing might leave her a sticky mewling mess."]},
{attribname: "increased fluids", descs: ["","Her body produces much more fluids than normal. She gets wet easily, and lubrication will never be a problem, although cleanup might be."]},
{attribname: "always ready", descs: ["","Her body is always ready for sex. Her nipples are perpetually stiff, and her pussy dripping wet."]},
{attribname: "enhanced orgasms", descs: ["","Her orgasms last longer and are more powerful and pleasurable than normal. It'll be hard to stay quiet or maintain her composure whenever they happen.","Her orgasms are mind-blowingly intense and incredibly drawn out. When they hit, she'll be incapacitated as her mind goes blank, unable to stop herself from writhing and moaning in bliss."]},
{attribname: "submissiveness", descs: ["","She has become submissive, seeking to obey and please, especially in sexual situations.","She's very submissive, always seeking to obey and please. She gets turned on and finds it really hard to resist when she's ordered around."]},
{attribname: "lust crest", descs: ["","She has been marked with a cursed tattoo over her womb. It glows brightly when she's horny.","She has been marked with a cursed tattoo over her womb. It glows brightly when she's horny. After enough creampies the heart shaped center will stay pink forever, making her 100% fertile and giving her a powerful orgasm each time cum enters her womb."]},
{attribname: "multiple orgasms", descs: ["","Her refractory period is basically non-existent, she's ready to go again right after she comes. If she gets too excited she'll experience a cascading wave of multiple orgasms, with no respite."]},
{attribname: "random orgasms", descs: ["","She'll occasionally experience random, uncontrollable orgasms at unpredictable times of the day, coming with little or no warning. "]},
{attribname: "triggered orgasms", descs: ["","She now has an implanted trigger phrase <b>'Good girl'</b>. Whenever she reads or hears it, she'll immediately find herself experiencing a powerful, uncontrollable orgasm."]},
{attribname: "triggered arousal", descs: ["","She now has an implanted trigger word <b>'Spark'</b>. Whenever she reads or hears it, she'll suddenly find herself extremely horny."]},
{attribname: "easily aroused", descs: ["","It's much easier to get her hot and bothered now. Seeing anything remotely sexual will get her all riled up, blushing and thinking of sex."]},
{attribname: "hair trigger", descs: ["","It's really easy to make her orgasm now. Any sexual stimulation will quickly push her over the edge."]},
{attribname: "flexible", descs: ["","Her body is very flexible and has great range of motion. All her orifices are a lot more stretchy and she'll be able to accomodate anything without much pain."]},
{attribname: "mutual orgasms", descs: ["","She will have an intense orgasm every time the last person she had sex with cums."]},
{attribname: "tasty fluids", descs: ["", "Her sexual fluids are super delicious, and anyone tasting them would be eager for more."]},
{attribname: "pheromones", descs: ["","Her body constantly emits special pheromones, gradually making everyone around her hornier and hornier. It's especially potent in enclosed spaces."]},
{attribname: "no gag reflex", descs: ["","Her gag reflex is greatly suppressed, making her able to take any size dick in her throat without choking."]},
{attribname: "oral lover", descs: ["","She loves oral sex. The thought of tasting and sucking with her sensitive lips and tongue greatly excites her."]},
{attribname: "anal lover", descs: ["","She love taking it from behind. The thought getting fucked in the ass greatly excites her - and it'll feel amazing too."]},
{attribname: "infertile", descsM: ["","You are shooting blanks. You'll never have to worry about accidentally impregnating someone."], descsF: ["","She is nearly imposible to get pregnant. It would take persistance, dedication, and a good amount of luck."]},
{attribname: "very fertile", descsM: ["","Your seed is especially potent. Going without contraception would almost guarantee pregnancy."],descsF: ["","She is exceptionally fertile. Most contraception won't prevent pregnancy. Condoms are the best bet."]},
{attribname: "pent up", descs: ["","Whenever she gets aroused, she can't 'cool down' and will remain aroused until she has an orgasm."]},
{attribname: "masochistic", descs: ["","Pain and degradation inflicted on her triggers pleasure and involuntary sexual arousal."]},
{attribname: "exhibitionist", descs: ["","She craves the risk of being exposed in public. She loves the thought of being caught naked or getting off where she shouldn't."]},
{attribname: "lewd dreams", descs: ["","She often has highly erotic dreams. She'll wake up each day a horny mess."]},
{attribname: "heat", descs: ["","For one day each month she'll enters a state of animalistic heat, barely able to focus on anything but being fucked and bred."]},
{attribname: "dependent", descs: ["","She finds it impossible to get off on her own. Whether with toys or her own hands. It'll feel good, but won't quite get her there. She'll need to find someone else to help her out."]},
{attribname: "fluid addiction", descs: ["","She's physically addicted to cum, if she goes without it, she'll crave it and feel withdrawl symptoms."]},
{attribname: "potent partner", descs: ["","The curse will cause the last person she had sex with to have no refractory period.","The curse will cause the last person she had sex with to have no refractory period and produce 50x as much as cum."]},
{attribname: "breeding fetish", descs: ["","She is turned on by the thought of someone knocking her up.","She is very turned on by the thought of someone knocking her up and keeping her as their breeder."]},
{attribname: "hair removal", descs: ["","She's completely hairless from the neck down, permanently. She won't ever have to worry about body hair."]},
{attribname: "sleepy", descs: ["","She is an incredibly heavy sleeper. Anything could happen to her while she's asleep and she won't wake up."]},
{attribname: "ditzy", descs: ["","She's kind of scatterbrained at times. She's get distracted easily and finds it hard to focus for long when thinking about anything too complicated."]},
{attribname: "noisy", descs: ["","She can't help but whimper and moan when pleasured. It'll be impossible for her to stay quiet when she orgasms."]},
{attribname: "denial", descs: ["","Whenever she's about to orgasm there's a 10% chance she'll instead be unable to cum for the next hour. She'll feel good but she won't be able to get over the edge, leaving her horny and frustrated.","Whenever she's about to orgasm there's a 30% chance she'll instead be unable to cum for the next 2 hours. She'll feel good but she won't be able to get over the edge, leaving her incredibly horny and frustrated."]},
{attribname: "palette swap", descs: ["",""]},
{attribname: "name change", descs: ["",""]},
];

var configChangeDescs = [ //used to describe detailed changing to this level
{attribname: "strength", descs:["","She flexes apprehensively, feeling a little stronger.","She flexes apprehensively, feeling a little stronger.","She flexes, feeling the power flowing through and shaping the muscles in her limbs, transforming them."]},
{attribname: "hair length", descs:["","Her hair lengthens slightly, stopping just at the base of her neck.","Her hair lengthens, stopping at her shoulders.","Her hair lengthens, flowing down past her upper back.","Her hair lengthens, extending down to her waist in lush, lustrous strands."]},
{attribname: "breast size", descs:["","Two soft, small mounds form from her chest. She's got boobs!","Her small breasts expand a little more.","Her small breasts expand a little more.","She can clearly feel the weight of her boobs now, as they expand.","She can clearly feel the weight of her boobs now, as they expand.","She gasps as her voluptuous boobs expand to huge proportions.","She gasps as her voluptuous boobs expand to massive proportions.","She gasps as her voluptuous boobs balloon to gigantic proportions."]},
{attribname: "ass size", descs:["","Her formerly flat butt seems to swell and round out a little as it grows.","Her ass expands further, as soft and jiggly flesh fills and forms into a nice bubble butt.","She gasps as her ass jiggles and expands further, ballooning into even thicker and curvier proportions.","She gasps as her ass inflates up to a gigantic size, a huge fleshy mass that jiggles and sways every time you move."]},
{attribname: "increased libido", descs:["","It doesn't feel like much has changed, but she starts to notice a pleasant, warm hunger in her pussy.","The tingle in her pussy grows, and she feels the pulsing desire inside her grow more urgent, a warm heat now increasingly craving for relief.","An intense, uncontrollable passion fills her trembling body. She finds it hard to focus on anything but a burning need to orgasm, as her hands reach down to pleasure herself."]},
{attribname: "increased sensitivity", descs:["","She brushes her chest experimentally and bucks her hips a bit, surprised by how good it feels.","Her eyes lose focus and she gasps as the change takes hold. She begins rubbing her thighs together and her knees buckle. The sensations are overwhelming."]},
{attribname: "random orgasms", descs:["","She is now cursed with random orgasms. From time to time they'll wash over her with no warning, hitting her with full force and leaving her dazed. Going out in public will be risky now."]},
{attribname: "triggered orgasms", descs:["","She hears a voice whispering a word, and her body tenses up as a warmth builds. She can try to resist, but she's soon quivering uncontrollably as an orgasm crashes through her."]},
{attribname: "triggered arousal", descs:["","She hears a voice whispering a word, and she's suddenly feeling flushed and horny, her pussy wet and needy."]},
{attribname: "easily aroused", descsM:["","As the change washes over you, you feel your cock stirring and slowly getting stiff and erect."],descsF:["","As the change washes over her, her nipples harden and her hand drifts toward her inner thigh."]},
];

var configChangeImgs = [ //used to show icons for attribute at this level
{attribname: "strength", imgsM:["enfeebledF.jpg","strengthF.jpg"], imgsF:["enfeebledF.jpg","strengthF.jpg"]},
{attribname: "stamina", imgsM:["enervatedF.jpg","staminaF.jpg"], imgsF:["enervatedF.jpg","staminaF.jpg"]},
{attribname: "dexterity", imgsM:["clumsyF.jpg","dexterityF.jpg"], imgsF:["clumsyF.jpg","dexterityF.jpg"]},
{attribname: "eyesight", imgsM:["eyesightF.jpg","eyesight.jpg"], imgsF:["eyesightF.jpg","eyesight.jpg"]},
{attribname: "constitution", imgs:["constitution.jpg"]},
{attribname: "intelligence", imgs:["intelligence.jpg"]},
{attribname: "charisma", imgsM:["wallflowerF.jpg","charisma.jpg"], imgsF:["wallflowerF.jpg","charisma.jpg"]},
{attribname: "talent", imgsM:["talentM.jpg"], imgsF:["talentF.jpg"]},
{attribname: "luck", imgs:["unlucky.jpg","luck.jpg"]},
{attribname: "breast size", imgs:["chest1.jpg","chest2.jpg","chest3.jpg","chest4.jpg","chest5.jpg","chest6.jpg","chest7.jpg","chest8.jpg"]},
{attribname: "hair length", imgs:["","hair1.jpg","hair2.jpg","hair3.jpg","hair4.jpg"]},
{attribname: "ass size", imgs:["ass1.jpg","ass2.jpg","ass3.jpg","ass4.jpg","ass5.jpg"]},
{attribname: "physique", imgs:["","physique1.jpg","physique2.jpg"]},
{attribname: "height", imgsM:["shrinkF.jpg"], imgsF:["shrinkF.jpg"]},
{attribname: "age", imgsM:["regressF.jpg"], imgsF:["regressF.jpg"]},
{attribname: "orientation", imgs:[]},
{attribname: "increased libido", imgsF:["","libidoF1.jpg","libidoF2.jpg","libidoF3.jpg"],imgsM:["","libidoF1.jpg","libidoF2.jpg","libidoF3.jpg"]},
{attribname: "increased sensitivity", imgs:["sensitive.jpg"]},
{attribname: "increased fluids", imgsM:["increasedfluidsF.jpg"], imgsF:["increasedfluidsF.jpg"]},
{attribname: "always ready", imgsM:["alwaysreadyF.jpg"], imgsF:["alwaysreadyF.jpg"]},
{attribname: "enhanced orgasms", imgsM:["enhancedF1.jpg","enhancedF1.jpg","enhancedF2.jpg"], imgsF:["enhancedF1.jpg","enhancedF1.jpg","enhancedF2.jpg"]},
{attribname: "submissiveness", imgs:["submissive.jpg"]},
{attribname: "lust crest", imgs:["lustcrest.jpg"]},
{attribname: "multiple orgasms", imgs:["multipleorgasms.jpg"]},
{attribname: "random orgasms", imgs:["randomorgasms.jpg"]},
{attribname: "triggered orgasms", imgs:["triggeredorgasms.jpg"]},
{attribname: "triggered arousal", imgs:["triggeredarousal.jpg"]},
{attribname: "easily aroused", imgsM:["easilyarousedF.jpg"], imgsF:["easilyarousedF.jpg"]},
{attribname: "hair trigger", imgsM:["hairtriggerF.jpg"], imgsF:["hairtriggerF.jpg"]},
{attribname: "flexible", imgsM:["flexibleF.jpg"], imgsF:["flexibleF.jpg"]},
{attribname: "mutual orgasms", imgs:["mutualorgasm.jpg"]},
{attribname: "tasty fluids", imgs:["tastyfluids.jpg"]},
{attribname: "pheromones", imgs:["pheromones.jpg"]},
{attribname: "no gag reflex", imgs:["nogag.jpg"]},
{attribname: "oral lover", imgsM:["oralloverF.jpg"], imgsF:["oralloverF.jpg"]},
{attribname: "anal lover", imgs:["anallover.jpg"]},
{attribname: "infertile", imgs:["infertile.jpg"]},
{attribname: "very fertile", imgs:["veryfertile.jpg"]},
{attribname: "pent up", imgs:["pentup.jpg"]},
{attribname: "masochistic", imgsM:["masochistF.jpg"], imgsF:["masochistF.jpg"]},
{attribname: "exhibitionist", imgs:["exhibitionist.jpg"]},
{attribname: "lewd dreams", imgs:["lewddreams.jpg"]},
{attribname: "heat", imgs:["heat.jpg"]},
{attribname: "dependent", imgs:["dependent.jpg"]},
{attribname: "fluid addiction", imgs:["fluidaddiction.jpg"]},
{attribname: "potent partner", imgs:["potentpartner.jpg"]},
{attribname: "breeding fetish", imgs:["breedingfetish.jpg"]},
{attribname: "hair removal", imgs:["hairremoval.jpg"]},
{attribname: "sleepy", imgsM:["sleepyF.jpg"], imgsF:["sleepyF.jpg"]},
{attribname: "ditzy", imgsM:["ditzyF.jpg"], imgsF:["ditzyF.jpg"]},
{attribname: "noisy", imgs:["noisy.jpg"]},
{attribname: "denial", imgs:["denial.jpg"]},
];


var configEffects = [
{category: "Transformation", effectname: "Strength Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"You will need strength or some may take advantage.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of power flow through her.</span><br/><br/><span style='color:lime'>(Strength Improved!)</span>", requiresattribnotmax:"strength"},
{category: "Transformation", effectname: "Stamina Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"Much will be demanded of you. You will need stamina to keep up.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of newfound endurance flow through her. She has new energy reserves just waiting to be tapped.</span><br/><br/><span style='color:lime'>(Stamina Improved!)</span>", requiresattribnotmax:"stamina"},
{category: "Transformation", effectname: "Dexterity Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"Be nimble. Be quick. You;ll need it for the trials ahead.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of agility flow through her. She feels quicker, her movements more coordinated and precise.</span><br/><br/><span style='color:lime'>(Dexterity Improved!)</span>", requiresattribnotmax:"dexterity"},
{category: "Transformation", effectname: "Constitution Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"Your body will be put through it paces. You'll need to recover quickly. \"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of life flow through her, rejuvinating and revitalizing her body.</span><br/><br/><span style='color:lime'>(Constitution Improved!)</span>", requiresattribnotmax:"constitution"},
{category: "Transformation", effectname: "Intelligence Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"Will you be able to think your way out? Or is ignorance bliss?\"</em></span><br/><br/><span style='float:right'>As the words form, she feels her mind sharpen, her thoughts expanding to a whole new level.</span><br/><br/><span style='color:lime'>(Intelligence Improved!)</span>",requiresattribnotmax:"intelligence"},
{category: "Transformation", effectname: "Charisma Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"You have a pretty face and a quick tongue. There's more than one way to use them.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of confidence and poise.</span><br/><br/><span style='color:lime'>(Charisma Improved!)</span>",requiresattribnotmax:"charisma"},
{category: "Transformation", effectname: "Talent Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"You don't have the skills you need for the coming trials. You had best learn them.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a surge of inspiration. She feels more capable, more competent.</span><br/><br/><span style='color:lime'>(Talent Improved!)</span>",requiresattribnotmax:"talent"},
{category: "Transformation", effectname: "Luck Enhancement", img:"none", desc: "<span style='color:yellow'><em>\"The odds are stacked aginst you. You'll need luck on your side.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels luckier than before, though she can't quite explain how.</span><br/><br/><span style='color:lime'>(Luck Improved!)</span>",requiresattribnotmax:"luck"},
{category: "CursedTransformation", effectname: "Hair Growth", img:"none", desc: "<span style='color:yellow'><em>\"Your hair is beautiful, feminine, and the perfect grip from behind. More is better.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a slight itch from her scalp and her hair rapidly grows longer.</span><br/><br/><span style='color:lime'>(Hair Length Increased!)</span>",requiresattribnotmax:"hair length",randwt:1},
{category: "CursedTransformation", effectname: "Enfeeblement", img:"none", desc: "<span style='color:yellow'><em>\"The weaker you are, the easier it will be to take advantage of you. \"</em></span><br/><br/><span style='float:right'>As the words form, the muscles in her arms and legs begin shrinking, becoming soft and smooth.</span><br/><br/><span style='color:lime'>(Enfeebled!)</span>", requiresattribnotmin:"strength"},
{category: "CursedTransformation", effectname: "Breast Growth", img:"none", desc: "<span style='color:yellow'><em>\"Nothing attracts attention like big tits. Let's make sure you get noticed.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a slight tenderness in her chest and looks down in shock. Her boobs are expanding and swelling!</span><br/><br/><span style='color:lime'>(Breast Size Increased!)</span>",requiresattribnotmax:"breast size",randwt:4},
{category: "CursedTransformation", effectname: "Extra Feminization", img:"none", desc: "<span style='color:yellow'><em>\"We'll make you the ideal woman, with a body to match.\"</em></span><br/><br/><span style='float:right'>As the words form, her body begins to transform, her waist narrowing as her hips widen. Her face and skin becoming softer and smoother. She lets out a soft gasp, as her chest and butt grow slightly, feeling tighter and fuller. </span><br/><br/><span style='color:lime'>(Extra Feminization!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"physique",randwt:4},
{category: "CursedTransformation", effectname: "Shrinking", img:"none", desc: "<span style='color:yellow'><em>\"Men don't want a towering Amazon. We'll make you fun-sized.\"</em></span><br/><br/><span style='float:right'>As the words form, she briefly seems to be under an enormous weight, head and shoulders dipping. Looking again it's clear that she has gotten just a little shorter.</span><br/><br/><span style='color:lime'>(Height Decreased!)</span>",requiresattribcustom:"height"},
{category: "CursedTransformation", effectname: "Ass Expansion", img:"none", desc: "<span style='color:yellow'><em>\"Let's fill out those jeans. You need more cushion for pushin'.\"</em></span><br/><br/><span style='float:right'>As the words form, she gasps as the change takes hold and her ass begins expanding, soft fat forming into shape.</span><br/><br/><span style='color:lime'>(Ass Expansion!)</span>",requiresattribnotmax:"ass size",randwt:1},
{category: "CursedTransformation", effectname: "Orientation Change", img:"orientation.jpg", desc: "<span style='color:yellow'><em>\"Things aren't always what they seem, why not pick a different team?\"</em></span><br/><br/><span style='float:right'>As the words form, you feel a subtle shift within your mind... and as you reflect, you're slightly unsettled to discover your sexual orientations have changed.</span><br/><br/><span style='color:lime'>(Orientation Changed!)</span>",requiresattribcustom:"orientation",randwt:1},
{category: "CursedTransformation", effectname: "Increased Libido", img:"none", desc: "<span style='color:yellow'><em>\"Your sex drive needs an overhaul. Let's fire you up.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a strange tingle rush through her body. </span><br/><br/><span style='color:lime'>(Libido Increased!)</span>",requiresattribnotmax:"increased libido",randwt:3},
{category: "CursedTransformation", effectname: "Increased Sensitivity", img:"none", desc: "<span style='color:yellow'><em>\"It's much harder to ignore your urges when everything feels good.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a strange tingle rush over her skin.</span><br/><br/><span style='color:lime'>(Sensitivity Increased!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"increased sensitivity",randwt:1},
{category: "CursedTransformation", effectname: "Increased Fluids", img:"none", desc: "<span style='color:yellow'><em>\"You're going to spend a lot of time with you legs spread. It would be a shame to waste money on lube.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a dampness build between her legs.</span><br/><br/><span style='color:lime'>(Fluid Production Increased!)</span>",requiresattribnotmax:"increased fluids"},
{category: "CursedTransformation", effectname: "Always Ready", img:"none", desc: "<span style='color:yellow'><em>\"Who knows when you'll have sex? It's safer to just always be prepared.\"</em></span><br/><br/><span style='float:right'>As the words form, a tingle runs over her body and she feels a dampness build between her legs.</span><br/><br/><span style='color:lime'>(Always Ready!)</span>",requiresattribnotmax:"always ready"},
{category: "CursedTransformation", effectname: "Enhanced Orgasms", img:"none", desc: "<span style='color:yellow'><em>\"Twice the length, and triple the high, this new change will blow your mind.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Orgasms Enhanced!)</span>",requiresattribnotmax:"enhanced orgasms"},
{category: "CursedTransformation", effectname: "Submissiveness", img:"none", desc: "<span style='color:yellow'><em>\"Making your own decisions is exhausting. Be a good girl and do as you're told.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Submissiveness Increased!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"submissiveness"},
//{category: "CursedTransformation", effectname: "Hypnotic Susceptibility", img:"none", desc: "<span style='color:yellow'><em>\"Listen to my voice. Listen to the rhythm. You're eyes are getting heavy.\"</em></span><br/><br/><span style='float:right'>As the words form, the tension leaves her body and her eyes briefly lose focus as a warm feeling washes over her mind, before she manages to snap back to alertness.</span><br/><br/><span style='color:lime'>(Hypnotic Susceptibility Increased!)</span>",requiresattribnotmax:"hypnotic susceptibility"},
{category: "CursedTransformation", effectname: "Multiple Orgasms", img:"none", desc: "<span style='color:yellow'><em>\"You don't need limits. See how many times you can reach your peak without burning out.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Multiple Orgasms!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"multiple orgasms"},
{category: "CursedTransformation", effectname: "Random Orgasms", img:"none", desc: "<span style='color:yellow'><em>\"All the reward with none of the work. Shame you can't control it.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Random Orgasms!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"random orgasms"},
{category: "CursedTransformation", effectname: "Triggered Orgasms", img:"none", desc: "<span style='color:yellow'><em>\"We've implanted a word to make you moan. Be careful with who knows.\"       </em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Triggered Orgasms!)  </span>",requiresattribnotmin:"gender",requiresattribnotmax:"triggered orgasms"},
{category: "CursedTransformation", effectname: "Triggered Arousal", img:"none", desc: "<span style='color:yellow'><em>\"We've implanted a word to wind you up. Be careful with who knows.\"         </em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Triggered Arousal!)  </span>",requiresattribnotmin:"gender",requiresattribnotmax:"triggered arousal"},
{category: "CursedTransformation", effectname: "Easily Aroused", img:"none", desc:    "<span style='color:yellow'><em>\"No one will need to romance you. It won't take much to get you going.\"     </em></span><br/><br/><span style='float:right'>As the words form, she gasps and a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Easily Aroused!)   </span>",requiresattribnotmax:"easily aroused"},
{category: "CursedTransformation", effectname: "Hair Trigger", img:"none", desc:      "<span style='color:yellow'><em>\"You'll only ever be a few strokes from bliss. Is it a blessing or curse?\"  </em></span><br/><br/><span style='float:right'>As the words form, she gasps and a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Hair Trigger!)   </span>",requiresattribnotmax:"hair trigger"},
{category: "CursedTransformation", effectname: "Flexible",img:"none", desc: "<span style='color:yellow'><em>\"Stretchy like rubber and supple as a reed, your flexibility is guaranteed.\"</em></span><br/><br/><span style='float:right'>As the words form, she gives a slight stretch, her joints seeming to loosen.</span><br/><br/><span style='color:lime'>(Flexible!)</span>",requiresattribnotmax:"flexible"},
//{category: "CursedTransformation", effectname: "Cheerful", img:"none", desc: "<span style='color:yellow'><em>\"Why don't you smile? You're so much prettier that way.\"</em></span><br/><br/><span style='float:right'>As the words form, she giggles as an inexplicable wave of happiness and contentment washes over her.</span><br/><br/><span style='color:lime'>(Cheerful!)</span>",requiresattribnotmax:"cheerful"},
{category: "CursedTransformation", effectname: "Tasty Fluids", img:"none", desc: "<span style='color:yellow'><em>\"Some will want to taste honey straight from the tap. Yours won't disappoint.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Tasty Fluids!)</span>",requiresattribnotmax:"tasty fluids"},
{category: "CursedTransformation", effectname: "Pheromones", img:"none", desc: "<span style='color:yellow'><em>\"You'll have no trouble attracting attention. It must be something in the air.\"</em></span><br/><br/><span style='float:right'>As the words form, a faint pleasant smell becomes noticeable in the air.</span><br/><br/><span style='color:lime'>(Pheromones!)</span>",requiresattribnotmax:"pheromones"},
{category: "CursedTransformation", effectname: "No Gag Reflex", img:"none", desc: "<span style='color:yellow'><em>\"No excuses once you're on your knees. You'll be up to any challenge.\"</em></span><br/><br/><span style='float:right'>As the words form, she gives what looks like a hiccup and reaches up to gently rub her throat.</span><br/><br/><span style='color:lime'>(No Gag Reflex!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"no gag reflex"},
{category: "CursedTransformation", effectname: "Oral Lover", img:"none", desc: "<span style='color:yellow'><em>\"What fun is an oral fixation? Let's make it an obsession.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a slight tingle and begins absentmindedly tracing a finger across her bottom lip.</span><br/><br/><span style='color:lime'>(Oral Lover!)</span>",requiresattribnotmax:"oral lover"},
{category: "CursedTransformation", effectname: "Anal Lover", img:"none", desc: "<span style='color:yellow'><em>\"Don't play favorites with your pussy when there's a perfectly good hole right next door.\"</em></span><br/><br/><span style='float:right'>As the words form, shes feels a tingling in her butt and jumps, gasping at the unexpected pleasant sensitivity.</span><br/><br/><span style='color:lime'>(Anal Lover!)</span>",requiresattribnotmax:"anal lover"},
{category: "CursedTransformation", effectname: "Infertile", img:"none", desc: "<span style='color:yellow'><em>\"We've made sure having kids to almost impossible. On the plus side, no one is ever pulling out again.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a brief cramp pass through her.</span><br/><br/><span style='color:lime'>(Infertile!)</span>",requiresattribcustom:"infertile"},
{category: "CursedTransformation", effectname: "Very Fertile", img:"none", desc: "<span style='color:yellow'><em>\"Find a good stud. Your pussy is made for breeding.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a brief cramp pass through her.</span><br/><br/><span style='color:lime'>(Very Fertile!)</span>",requiresattribcustom:"very fertile"},
{category: "CursedTransformation", effectname: "Pent Up", img:"none", desc: "<span style='color:yellow'><em>\"Once you're wound up there's no coming down unless it's over the far side of the peak.\"</em></span><br/><br/><span style='float:right'>As the words form, she begins to feel warm and notices a lingering tension in her body.</span><br/><br/><span style='color:lime'>(Pent Up!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"pent up"},
{category: "CursedTransformation", effectname: "Masochistic", img:"none", desc: "<span style='color:yellow'><em>\"We've crossed some wires. You'll love being put in your place.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Masochistic!)</span>",requiresattribnotmax:"masochistic"},
{category: "CursedTransformation", effectname: "Exhibitionist", img:"none", desc: "<span style='color:yellow'><em>\"You should show someone how much you've changed. We're sure you'll both enjoy it.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Exhibitionist!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"exhibitionist"},
{category: "CursedTransformation", effectname: "Lewd Dreams", img:"none", desc: "<span style='color:yellow'><em>\"For some sleep is an escape. For you, it will be more of the same.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Lewd Dreams!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"lewd dreams"},
{category: "CursedTransformation", effectname: "Age Regression", img:"none", desc: "<span style='color:yellow'><em>\"These curses will last until you're a year older than you started. Let's add time for you to enjoy.\"</em></span><br/><br/><span style='float:right'>As the words form, the years seem to slip from her face and body. She has become younger.</span><br/><br/><span style='color:lime'>(Age Regression!)</span>",requiresattribcustom:"age",randwt:1},
{category: "CursedTransformation", effectname: "Heat", img:"none", desc: "<span style='color:yellow'><em>\"Give in to your animal urges.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Heat!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"heat"},
{category: "CursedTransformation", effectname: "Wallflower", img:"none", desc: "<span style='color:yellow'><em>\"A crowd can be stressful with all the attention. Stick to the sidelines.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Wallflower!)</span>",requiresattribnotmin:"charisma"},
{category: "CursedTransformation", effectname: "Dependent", img:"none", desc: "<span style='color:yellow'><em>\"There are some things better left to others. You'll need to find a partner.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Dependent!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"dependent"},
{category: "CursedTransformation", effectname: "Fluid Addiction", img:"none", desc: "<span style='color:yellow'><em>\"Find a reliable source of protein. You won't be able to go without a salty bitter variety for long.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her. </span><br/><br/><span style='color:lime'>(Fluid Addiction!)</span>",requiresattribnotmax:"fluid addiction"},
//{category: "CursedTransformation", effectname: "Lactation", img:"none", desc: "<span style='color:yellow'><em>\"You'll likely be treated like an animal. Let's make sure you're a useful one.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a tender fullness in her chest.</span><br/><br/><span style='color:lime'>(Lactation!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"lactation"},
{category: "CursedTransformation", effectname: "Hair Removal", img:"none", desc: "<span style='color:yellow'><em>\"We'll smooth out your maintenance regimen.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a odd prickling sensation as all body hair below her neck begins to fall away.</span><br/><br/><span style='color:lime'>(Hair Removal!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"hair removal"},
{category: "CursedTransformation", effectname: "Sleepy", img:"none", desc: "<span style='color:yellow'><em>\"You'll look so peaceful when you sleep. Nothing will wake you.\"</em></span><br/><br/><span style='float:right'>As the words form, her eyelids droop a bit as she's suddenly sleepy, but she manages to shake herself awake.</span><br/><br/><span style='color:lime'>(Sleepy!)</span>",requiresattribnotmax:"sleepy"},
{category: "CursedTransformation", effectname: "Ditzy", img:"none", desc: "<span style='color:yellow'><em>\"So many thoughts and worries. Let's make those slip away.\"</em></span><br/><br/><span style='float:right'>As the words form, her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Ditzy!)</span>",requiresattribnotmax:"ditzy"},
{category: "CursedTransformation", effectname: "Noisy", img:"none", desc: "<span style='color:yellow'><em>\"Invest in a gag. You won't be able to stop yourself from letting everyone know how good you feel.\"</em></span><br/><br/><span style='float:right'>As the words form, a soft moan escapes her and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Noisy!)</span>",requiresattribnotmin:"gender",requiresattribnotmax:"noisy"},
{category: "CursedTransformation", effectname: "Orgasm Denial", img:"none", desc: "<span style='color:yellow'><em>\"Sometimes you'll find no release and be forced to keep riding the crest.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Orgasm Denial!)</span>",requiresattribnotmax:"denial"},
{category: "CursedTransformation", effectname: "Clumsy", img:"none", desc: "<span style='color:yellow'><em>\"Take care, or your adorable clumsiness will get you into trouble.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body and she seems slightly unsteady.</span><br/><br/><span style='color:lime'>(Clumsy!)</span>",requiresattribnotmin:"dexterity"},
{category: "CursedTransformation", effectname: "Glasses", img:"none", desc: "<span style='color:yellow'><em>\"Handicap or much needed splatter shield? Decide for yourself.\"</em></span><br/><br/><span style='float:right'>As the words form, her vision seems to blur. A moment later, a pair of thick glasses emerges from a slot in the terminal. Putting them on, it seems she can see clearly again.</span><br/><br/><span style='color:lime'>(Glasses!)</span>",requiresattribnotmin:"eyesight"},
{category: "CursedTransformation", effectname: "Palette Swap", img:"paletteswap.jpg", desc: "<span style='color:yellow'><em>\"A new look for a new you.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body and her hair and eyes shift in color.</span><br/><br/><span style='color:lime'>(Palette Swap!)</span>",requiresattribnotmax:"palette swap"},
{category: "CursedTransformation", effectname: "Name Change", img:"namechange.jpg", desc: "<span style='color:yellow'><em>\"You'll be nothing like the old you. She no longer exists.\"</em></span><br/><br/><span style='float:right'>As the words form, a heavy buzzing fills the room, causing both of you to briefly lose focus.</span><br/><br/><span style='color:lime'>(Name Change!)</span>",requiresattribnotmin:"gender", requiresattribnotmax:"name change",randwt:2},
{category: "CursedTransformation", effectname: "Bad Luck", img:"none", desc: "<span style='color:yellow'><em>\"The odds are already stacked against you, what's a bit more bad luck?\"</em></span><br/><br/><span style='float:right'>As the words form, she feels like her luck has turned for the worse, though she can't quite explain how.</span><br/><br/><span style='color:lime'>(Bad Luck!)</span>",requiresattribnotmin:"luck"},
{category: "CursedTransformation", effectname: "Lust Crest", img:"none", desc: "<span style='color:yellow'><em>\"This tattoo won't just mark you as a slut, it'll make you one.\"</em></span><br/><br/><span style='float:right'>As the words form, she feels a flash of pain across her lower abdomen and looks down in shock. She has a new intricate tattoo.</span><br/><br/><span style='color:lime'>(Slut Marked!)</span>",requiresattribnotmax:"lust crest"},
{category: "CursedTransformation", effectname: "Mutual Orgasms", img:"none", desc: "<span style='color:yellow'><em>\"Satisfy your partner and you'll reap the rewards.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Mutual Orgasms!)</span>",requiresattribnotmax:"mutual orgasms"},
{category: "CursedTransformation", effectname: "Potent Partner", img:"none", desc: "<span style='color:yellow'><em>\"Your partner will be able to go and go. Hopefully you can handle it.\"</em></span><br/><br/><span style='float:right'>As the words form, a slight tingle runs over her body.</span><br/><br/><span style='color:lime'>(Potent Partner!)</span>",requiresattribnotmax:"potent partner"},
{category: "CursedTransformation", effectname: "Breeding Fetish", img:"none", desc: "<span style='color:yellow'><em>\"Knock Knock. Who's there? You Mommy, bred and happy.\"</em></span><br/><br/><span style='float:right'>As the words form, she takes a sharp breath and her eyes briefly lose focus as a wave seems to pass through her.</span><br/><br/><span style='color:lime'>(Breeding Fetish!)</span>",requiresattribnotmax:"breeding fetish"},

];


var playerTemplates = [
{"name":"Sarah","last name":"Temple","age":33,"height":173,"gender":1,"hair color":"Auburn","eye color":"Brown",
"desc":"Sarah Temple is a smart, independent girl. She'd be perfect if not for her almost non-existent sex-drive, and reluctance to do anything other than missionary.<br/>", 
"gear":[{name:"Passcode: Protection", qty:0},{name:"Passcode: Unlocking", qty:0},{name:"Passcode: Jaunting", qty:0},{name:"Silver Coin", qty:0}],
"strength":1,
"stamina":1,
"dexterity":1,
"eyesight":0,
"constitution":1,
"intelligence":1,
"charisma":0,
"talent":1,
"luck":1,
"breast size":2,
"hair length":2,
"physique":0,
"ass size":0,},
{"name":"Liz","last name":"Williams","age":30,"height":184,"gender":1,"hair color":"Brown","eye color":"Hazel",
"desc":"Liz Williams is cheerful and energetic. She wants kids but finds an issue with everyone she dates, and can't settle down.<br/>", 
"gear":[{name:"Passcode: Protection", qty:0},{name:"Passcode: Unlocking", qty:0},{name:"Passcode: Jaunting", qty:0},{name:"Silver Coin", qty:0}],
"strength":1,
"stamina":1,
"dexterity":1,
"eyesight":0,
"constitution":1,
"intelligence":1,
"charisma":1,
"talent":1,
"luck":1,
"breast size":1,
"hair length":1,
"physique":0,
"ass size":1,},
{"name":"Rachel","last name":"Baskin","age":25,"height":168,"gender":1,"hair color":"Auburn","eye color":"Green",
"desc":"Rachel is an odd, lonely girl who'd rather stay home with her cats than try to meet someone new.<br/>", 
"gear":[{name:"Passcode: Protection", qty:0},{name:"Passcode: Unlocking", qty:0},{name:"Passcode: Jaunting", qty:0},{name:"Silver Coin", qty:0}],
"strength":0,
"stamina":0,
"dexterity":0,
"eyesight":0,
"constitution":0,
"intelligence":1,
"charisma":0,
"talent":1,
"luck":1,
"breast size":0,
"hair length":1,
"physique":0,
"ass size":0,},
{"name":"Lena","last name":"Scott","age":28,"height":164,"gender":1,"hair color":"Black","eye color":"Brown",
"desc":"Lena is a holier-than-thou church girl saving herself for marriage. She loudly judges everyone for their sins.<br/>", 
"gear":[{name:"Passcode: Protection", qty:0},{name:"Passcode: Unlocking", qty:0},{name:"Passcode: Jaunting", qty:0},{name:"Silver Coin", qty:0}],
"strength":0,
"stamina":0,
"dexterity":1,
"eyesight":0,
"constitution":1,
"intelligence":0,
"charisma":0,
"talent":0,
"luck":0,
"breast size":0,
"hair length":1,
"physique":0,
"ass size":2,},
{"name":"Ameilia","last name":"Mahoney","age":19,"height":170,"gender":1,"hair color":"Blonde","eye color":"Green",
"desc":"Ameilia is hot and she knows it. Unfortunately she's also an unrelenting cock-tease.<br/>", 
"gear":[{name:"Passcode: Protection", qty:0},{name:"Passcode: Unlocking", qty:0},{name:"Passcode: Jaunting", qty:0},{name:"Silver Coin", qty:0}],
"strength":0,
"stamina":1,
"dexterity":1,
"eyesight":1,
"constitution":1,
"intelligence":0,
"charisma":1,
"talent":0,
"luck":1,
"breast size":1,
"hair length":0,
"physique":1,
"ass size":1,},
{"name":"Jane","last name":"Smith","age":24,"height":180,"gender":1,"hair color":"Brown","eye color":"Hazel",
"desc":"", //hidden sandbox character, do not remove
"gear":[],
"strength":1,
"stamina":1,
"dexterity":1,
"eyesight":1,
"constitution":1,
"intelligence":1,
"charisma":1,
"talent":1,
"luck":1,
"breast size":0,
"hair length":0,
"physique":0,
"ass size":0,}
];

var items = [
//valuable consumables
{name:"Silver Coin",desc:"In-game currency.", effect:"May be used to purchase in-game items.", img:"silvercoin.png", usable:false, stacks:true, randwt:3, gameitm:1},
{name:"Cash",desc:"Real world currency", effect:"This money will be transferred to your bank account every month as long as you are cursed.", img:"cash.jpg", usable:false, stacks:true, randwt:7},

//glyphs sold by shop
{name:"Passcode: Jaunting", desc:"", effect:"Moves your piece 6 steps forward when activated.",  img:"glyph2.jpg", usable:true, stacks:true, gameitm:1},
{name:"Passcode: Protection", desc:"", effect:"Grants protection against curses when activated.",  img:"glyph1.jpg", usable:false, stacks:true, gameitm:1},
{name:"Passcode: Unlocking", desc:"", effect:"Used to disarm potential traps in loot chests.",  img:"glyph3.jpg", usable:false, stacks:true, gameitm:1},

// These were item concepts once, but they've been removed during the streamlining of the game

//cursed items, single use, no stack
//{name:"Juliet's Amulet", desc:"A tarnished brass amulet set with a pink gemstone.", effect:"When equipped, transforms you into a girl named Juliet.",  img:"", usable:true, cursed:true, isconsumed:false, multiuse:false, stacks:false},
//{name:"Mood Ring", desc:"A plain ring that seems to be stuck on the color red.", effect:"When equipped, this ring puts you in the mood... by making you horny.",  img:"", usable:true, cursed:true, isconsumed:false, multiuse:false, stacks:false},
//single use useful, no stack
//{name:"Blue Loaded Die", desc:"A six sided plastic die.", effect:"When equipped, adds a -1 modifier to all future dice rolls (except 1s).",  img:"", usable:true, cursed:false, isconsumed:false, multiuse:false, stacks:false},
//{name:"Green Loaded Die", desc:"A six sided plastic die.", effect:"When equipped, adds a +1 modifier to all future dice rolls (except 6s).",  img:"", usable:true, cursed:false, isconsumed:false, multiuse:false, stacks:false},
//{name:"Reset Button", desc:"A big red button labelled 'RESET'", effect:"When activated, Teleports you back to square one.",  img:"", usable:true, cursed:false, isconsumed:false, multiuse:false, stacks:false},
//{name:"Disguise Kit", desc:"A box filled with vibrantly colored powders.", effect:"When equipped, gives you brown hair and eyes.",  img:"", usable:true, cursed:false, isconsumed:true, multiuse:true, stacks:true},
//{name:"Growth Serum", desc:"A vial containing a green liquid.", effect:"Drink this potion to grow taller. Also ages you slightly.",  img:"", usable:true, cursed:false, isconsumed:true, multiuse:true, stacks:true},
//{name:"Yin-Yang Scroll", desc:"A crumpled old scroll with the yin-yang symbol drawn on it.", effect:"When activated, switches your orientation.",  img:"", usable:true, cursed:false, isconsumed:true, multiuse:true, stacks:false},
//{name:"Hair Scissors", desc:"A pair of steel haircut scissors.", effect:"When activated, trims your hair short.",  img:"", usable:true, cursed:false, isconsumed:false, multiuse:false, stacks:false},
//flavor items, single use, no stack
//{name:"Leather Briefcase", desc:"A nondescript leather briefcase.", effect:"Contains $20,000 in legitimate unmarked bills.",  img:"", usable:false, stacks:false},
//{name:"Toy Wand", desc:"A short stick made of cheap plastic.", effect:"Allows the user to conjure any object made of plastic that's smaller than a toaster. Objects disappear in 24 hours.",  img:"", usable:false, stacks:false},
//{name:"Thinking Cap", desc:"A blue baseball cap.", effect:"Allows the wearer to hear the surface thoughts of anyone within 10 feet.",  img:"", usable:false, stacks:false},
//{name:"Unbreakable Rope", desc:"A coil of thin rope, about 10 feet.", effect:"This rope is unbreakable, and also excellect for tying knots and binding things.",  img:"", usable:false, stacks:false},
//{name:"Hand Mirror", desc:"A handheld mirror with a polished surface.", effect:"This mirror shows a reflection of the environment, but from a week ago.",  img:"", usable:false, stacks:false},
//{name:"Sunglasses", desc:"A pair of stylish sunglasses.", effect:"Allows the wearer to see through clothing.",  img:"", usable:false, stacks:false},

];
